import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  banners: [
    {
      id: 1,
      link: "/category/smartphones",
      brandText: "noise",
      brandDetails: "SOUND BY BOSE",
      product: "Master Buds 2",
      price: "₹6,999",
      subText: "Chance to win iPhone16 | Notify me",
      bgColor: "bg-gradient-to-r from-gray-900 to-black",
      gradientMask: "from-gray-900 via-gray-900/80",
      imgSrc: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=400&auto=format&fit=crop",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 2,
      link: "/category/smartphones",
      brandText: "POCO",
      brandDetails: "| UrbanCart Exclusive",
      brandBadge: "bg-yellow-400 text-black px-1.5 py-0.5 rounded-sm font-bold text-[10px]",
      product: "POCO X8 Pro",
      price: "₹29,999",
      subText: "Sale starts on 23rd March, 12 PM",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/80",
      imgSrc: "https://images.unsplash.com/photo-1598327105666-5b89351cb315?q=80&w=400&auto=format&fit=crop",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 3,
      link: "/category/electronics",
      brandText: "SAMSUNG",
      brandDetails: "",
      product: "43\" 4K TVs!",
      price: "₹11,069",
      subText: "Crystal Clear. Crystal Powerful.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1593784991095-a205069470b6?q=80&w=400&auto=format&fit=crop",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 4,
      link: "/category/electronics",
      brandText: "APPLE",
      brandDetails: "SERIES 9",
      product: "Smartwatches",
      price: "₹32,499",
      subText: "The ultimate device for health.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=400&auto=format&fit=crop",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 5,
      link: "/category/electronics",
      brandText: "ASUS",
      brandDetails: "ROG",
      product: "Gaming Laptops",
      price: "₹74,990",
      subText: "GeForce RTX™ 40 Series.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=400&auto=format&fit=crop",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 6,
      link: "/category/appliances",
      brandText: "BOSCH",
      brandDetails: "FRONT LOAD",
      product: "Washing Machines",
      price: "₹24,500",
      subText: "AntiTangle technology. Whisper quiet.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1626806787426-5910811b6325?q=80&w=400&auto=format&fit=crop",
      textColor: "text-white",
      bankOffer: true,
    }
  ],
  recommendedProducts: [
    {
      id: 1,
      name: "Premium Wireless Earbuds",
      category: "Electronics",
      price: "₹4,999",
      originalPrice: "₹7,999",
      rating: 4.8,
      reviews: 124,
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=400&auto=format&fit=crop",
      discount: "37% OFF",
      isNew: true,
    },
    {
      id: 2,
      name: "Classic Leather Watch",
      category: "Accessories",
      price: "₹2,499",
      originalPrice: "₹3,999",
      rating: 4.5,
      reviews: 89,
      image: "https://images.unsplash.com/photo-1524592091214-84d5a4701e7c?q=80&w=400&auto=format&fit=crop",
      discount: "38% OFF",
    },
    {
      id: 3,
      name: "Minimalist Cotton Tee",
      category: "Fashion",
      price: "₹799",
      originalPrice: "₹1,499",
      rating: 4.3,
      reviews: 256,
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=400&auto=format&fit=crop",
      discount: "47% OFF",
    },
    {
      id: 4,
      name: "Ultra-Light Running Shoes",
      category: "Footwear",
      price: "₹3,299",
      originalPrice: "₹5,499",
      rating: 4.7,
      reviews: 167,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=400&auto=format&fit=crop",
      discount: "40% OFF",
      isNew: true,
    }
  ],
  ethnicProducts: [
    {
      id: 101,
      name: "Floral Embroidered Anarkali",
      category: "Women's Ethnic",
      price: "₹3,499",
      originalPrice: "₹5,499",
      rating: 4.8,
      reviews: 245,
      image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=400&auto=format&fit=crop",
      discount: "36% OFF",
      isNew: true,
    },
    {
      id: 102,
      name: "Royal Blue Silk Saree",
      category: "Sarees",
      price: "₹4,299",
      originalPrice: "₹7,999",
      rating: 4.9,
      reviews: 189,
      image: "https://images.unsplash.com/photo-1625910513397-22a99c1fe0b7?q=80&w=400&auto=format&fit=crop",
      discount: "46% OFF",
    },
    {
      id: 103,
      name: "Lucknowi Chikankari Kurta",
      category: "Men's Ethnic",
      price: "₹1,899",
      originalPrice: "₹2,999",
      rating: 4.6,
      reviews: 112,
      image: "https://images.unsplash.com/photo-1597983073453-ef4ff63b5235?q=80&w=400&auto=format&fit=crop",
      discount: "37% OFF",
    },
    {
      id: 104,
      name: "Gold Tone Heavy Earrings",
      category: "Jewellery",
      price: "₹999",
      originalPrice: "₹1,999",
      rating: 4.7,
      reviews: 356,
      image: "https://images.unsplash.com/photo-163001901962a-097c482227d3?q=80&w=400&auto=format&fit=crop",
      discount: "50% OFF",
      isNew: true,
    }
  ]
};

const HomeSlice = createSlice({
  name: "HomeSlice",
  initialState,
  reducers: {},
});

export default HomeSlice.reducer;
