import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  banners: [
    {
      id: 1,
      link: "/category/electronics",
      brandText: "noise",
      brandDetails: "SOUND BY BOSE",
      product: "Master Buds 2",
      price: "₹6,999",
      subText: "Chance to win iPhone16 | Notify me",
      bgColor: "bg-gradient-to-r from-gray-900 to-black",
      gradientMask: "from-gray-900 via-gray-900/80",
      imgSrc: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?q=80&w=800",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 2,
      link: "/category/electronics",
      brandText: "POCO",
      brandDetails: "| UrbanCart Exclusive",
      brandBadge: "bg-yellow-400 text-black px-1.5 py-0.5 rounded-sm font-bold text-[10px]",
      product: "POCO X8 Pro",
      price: "₹29,999",
      subText: "Sale starts on 23rd March, 12 PM",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/80",
      imgSrc: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 3,
      link: "/category/electronics",
      brandText: "SAMSUNG",
      brandDetails: "",
      product: "43\" 4K TVs!",
      price: "₹11,069",
      subText: "Crystal Clear. Crystal Powerful.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1593784991095-a205069470b6?q=80&w=800",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 4,
      link: "/category/electronics",
      brandText: "APPLE",
      brandDetails: "SERIES 9",
      product: "Smartwatches",
      price: "₹32,499",
      subText: "The ultimate device for health.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?q=80&w=800",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 5,
      link: "/category/electronics",
      brandText: "ASUS",
      brandDetails: "ROG",
      product: "Gaming Laptops",
      price: "₹74,990",
      subText: "GeForce RTX™ 40 Series.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800",
      textColor: "text-white",
      bankOffer: true,
    },
    {
      id: 6,
      link: "/category/appliances",
      brandText: "BOSCH",
      brandDetails: "FRONT LOAD",
      product: "Washing Machines",
      price: "₹24,500",
      subText: "AntiTangle technology. Whisper quiet.",
      bgColor: "bg-gradient-to-r from-black via-gray-900 to-gray-800",
      gradientMask: "from-black via-black/50",
      imgSrc: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=800",
      textColor: "text-white",
      bankOffer: true,
    }
  ],
  recommendedProducts: [
    {
      id: 1,
      name: "Premium Wireless Earbuds",
      category: "Electronics",
      price: "₹4,999",
      originalPrice: "₹7,999",
      rating: 4.8,
      reviews: 124,
      image: "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?q=80&w=800",
      discount: "37% OFF",
      isNew: true,
    },
    {
      id: 2,
      name: "Classic Leather Watch",
      category: "Accessories",
      price: "₹2,499",
      originalPrice: "₹3,999",
      rating: 4.5,
      reviews: 89,
      image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=800",
      discount: "38% OFF",
    },
    {
      id: 3,
      name: "Minimalist Cotton Tee",
      category: "Fashion",
      price: "₹799",
      originalPrice: "₹1,499",
      rating: 4.3,
      reviews: 256,
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800",
      discount: "47% OFF",
    },
    {
      id: 4,
      name: "Ultra-Light Running Shoes",
      category: "Footwear",
      price: "₹3,299",
      originalPrice: "₹5,499",
      rating: 4.7,
      reviews: 167,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800",
      discount: "40% OFF",
      isNew: true,
    }
  ],
  ethnicProducts: [
    {
      id: 101,
      name: "Biba Women's Cotton Straight Kurta",
      category: "Women's Ethnic",
      price: 1499,
      originalPrice: 2499,
      rating: 4.8,
      reviews: 245,
      image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
      discount: "36% OFF",
      isNew: true,
    },
    {
      id: 102,
      name: "Banarasi Art Silk Saree",
      category: "Sarees",
      price: 4299,
      originalPrice: 7999,
      rating: 4.9,
      reviews: 189,
      image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
      discount: "46% OFF",
    },
    {
      id: 103,
      name: "Manyavar Men's Blended Kurta and Churidar",
      category: "Men's Ethnic",
      price: 2999,
      originalPrice: 3999,
      rating: 4.6,
      reviews: 112,
      image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
      discount: "25% OFF",
    },
    {
      id: 104,
      name: "Zaveri Pearls Gold Tone Necklace Set",
      category: "Jewellery",
      price: 999,
      originalPrice: 1999,
      rating: 4.7,
      reviews: 356,
      image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
      discount: "50% OFF",
      isNew: true,
    }
  ]
};

const HomeSlice = createSlice({
  name: "HomeSlice",
  initialState,
  reducers: {},
});

export default HomeSlice.reducer;
